# Generated by Django 3.1.7 on 2021-05-03 07:49

import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('discriminator', models.CharField(db_column='Discriminator', max_length=255)),
            ],
            options={
                'db_table': 'user',
                'managed': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, db_column='Name', max_length=255, null=True)),
                ('address', models.CharField(blank=True, db_column='Address', max_length=255, null=True)),
                ('desc', models.CharField(blank=True, db_column='Desc', max_length=255, null=True)),
            ],
            options={
                'db_table': 'company',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, db_column='Name', max_length=255, null=True)),
                ('phone', models.CharField(blank=True, db_column='Phone', max_length=255, null=True)),
                ('address', models.CharField(blank=True, db_column='Address', max_length=255, null=True)),
            ],
            options={
                'db_table': 'customer',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Exportbill',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('date', models.DateField(blank=True, db_column='Date', null=True)),
                ('manager', models.IntegerField(blank=True, db_column='Manager', null=True)),
                ('customer', models.IntegerField(blank=True, db_column='Customer', null=True)),
                ('totalincome', models.FloatField(blank=True, db_column='TotalIncome', null=True)),
                ('discriminator', models.CharField(db_column='Discriminator', max_length=255)),
            ],
            options={
                'db_table': 'exportbill',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Importbill',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('date', models.DateField(blank=True, db_column='Date', null=True)),
                ('manager', models.IntegerField(blank=True, db_column='Manager', null=True)),
                ('provider', models.IntegerField(blank=True, db_column='Provider', null=True)),
            ],
            options={
                'db_table': 'importbill',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Importedmaterial',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('material', models.IntegerField(blank=True, db_column='Material', null=True)),
                ('price', models.FloatField(db_column='Price')),
            ],
            options={
                'db_table': 'importedmaterial',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, db_column='Name', max_length=255, null=True)),
                ('type', models.CharField(blank=True, db_column='Type', max_length=255, null=True)),
                ('desc', models.CharField(blank=True, db_column='Desc', max_length=255, null=True)),
                ('quantity', models.FloatField(blank=True, db_column='Quantity', null=True)),
                ('discriminator', models.CharField(db_column='Discriminator', max_length=255)),
            ],
            options={
                'db_table': 'material',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Materialinproduct',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'materialinproduct',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Materialofprovider',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('material', models.IntegerField(blank=True, db_column='Material', null=True)),
                ('price', models.FloatField(db_column='Price')),
                ('provider', models.IntegerField(blank=True, db_column='Provider', null=True)),
            ],
            options={
                'db_table': 'materialofprovider',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Materialofproviderinstorage',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('material', models.IntegerField(blank=True, db_column='Material', null=True)),
                ('quantity', models.FloatField(db_column='Quantity')),
            ],
            options={
                'db_table': 'materialofproviderinstorage',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Materialrequest',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'materialrequest',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('customer', models.IntegerField(blank=True, db_column='Customer', null=True)),
            ],
            options={
                'db_table': 'order',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Orderedproduct',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('price', models.FloatField(db_column='Price')),
                ('product', models.IntegerField(blank=True, db_column='Product', null=True)),
                ('quantity', models.IntegerField(db_column='Quantity')),
            ],
            options={
                'db_table': 'orderedproduct',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, db_column='Name', max_length=255, null=True)),
                ('type', models.CharField(blank=True, db_column='Type', max_length=255, null=True)),
                ('price', models.FloatField(db_column='Price')),
                ('desc', models.CharField(blank=True, db_column='Desc', max_length=255, null=True)),
                ('iddesign', models.CharField(blank=True, db_column='IdDesign', max_length=255, null=True)),
                ('quantity', models.IntegerField(blank=True, db_column='Quantity', null=True)),
                ('discriminator', models.CharField(db_column='Discriminator', max_length=255)),
            ],
            options={
                'db_table': 'product',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Productexported',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('quantity', models.IntegerField(db_column='Quantity')),
                ('price', models.FloatField(db_column='Price')),
                ('product', models.IntegerField(blank=True, db_column='Product', null=True)),
                ('productid', models.IntegerField(db_column='ProductID')),
            ],
            options={
                'db_table': 'productexported',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Progress',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, db_column='Name', max_length=255, null=True)),
                ('desc', models.CharField(blank=True, db_column='Desc', max_length=255, null=True)),
            ],
            options={
                'db_table': 'progress',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, db_column='Name', max_length=255, null=True)),
                ('address', models.CharField(blank=True, db_column='Address', max_length=255, null=True)),
                ('phone', models.CharField(blank=True, db_column='Phone', max_length=255, null=True)),
                ('desc', models.CharField(blank=True, db_column='Desc', max_length=255, null=True)),
            ],
            options={
                'db_table': 'provider',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Requestedmaterial',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('material', models.IntegerField(blank=True, db_column='Material', null=True)),
                ('quantity', models.FloatField(db_column='Quantity')),
            ],
            options={
                'db_table': 'requestedmaterial',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Storage',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, db_column='Name', max_length=255, null=True)),
                ('address', models.CharField(blank=True, db_column='Address', max_length=255, null=True)),
                ('desc', models.CharField(blank=True, db_column='Desc', max_length=255, null=True)),
                ('manager', models.IntegerField(blank=True, db_column='Manager', null=True)),
            ],
            options={
                'db_table': 'storage',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('product', models.IntegerField(blank=True, db_column='Product', null=True)),
            ],
            options={
                'db_table': 'task',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Taskprogress',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('progress', models.IntegerField(blank=True, db_column='Progress', null=True)),
                ('task', models.IntegerField(blank=True, db_column='Task', null=True)),
                ('startdate', models.DateField(blank=True, db_column='StartDate', null=True)),
                ('enddate', models.DateField(blank=True, db_column='EndDate', null=True)),
            ],
            options={
                'db_table': 'taskprogress',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Workshop',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, db_column='Name', max_length=255, null=True)),
                ('address', models.CharField(blank=True, db_column='Address', max_length=255, null=True)),
                ('desc', models.CharField(blank=True, db_column='Desc', max_length=255, null=True)),
            ],
            options={
                'db_table': 'workshop',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ExportbillListproduct',
            fields=[
                ('exportbillid', models.OneToOneField(db_column='ExportBillID', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='wood_producing.exportbill')),
                ('exportbillindex', models.IntegerField(db_column='ExportBillIndex')),
                ('listproduct', models.IntegerField(blank=True, db_column='ListProduct', null=True)),
            ],
            options={
                'db_table': 'exportbill_listproduct',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ImportbillListmaterial',
            fields=[
                ('importbillid', models.OneToOneField(db_column='ImportBillID', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='wood_producing.importbill')),
                ('importbillindex', models.IntegerField(db_column='ImportBillIndex')),
                ('listmaterial', models.IntegerField(blank=True, db_column='ListMaterial', null=True)),
            ],
            options={
                'db_table': 'importbill_listmaterial',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MaterialrequestListmaterial',
            fields=[
                ('materialrequestid', models.OneToOneField(db_column='MaterialRequestID', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='wood_producing.materialrequest')),
                ('materialrequestindex', models.IntegerField(db_column='MaterialRequestIndex')),
                ('listmaterial', models.IntegerField(blank=True, db_column='ListMaterial', null=True)),
            ],
            options={
                'db_table': 'materialrequest_listmaterial',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OrderListproduct',
            fields=[
                ('orderid', models.OneToOneField(db_column='OrderID', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='wood_producing.order')),
                ('orderindex', models.IntegerField(db_column='OrderIndex')),
                ('listproduct', models.IntegerField(blank=True, db_column='ListProduct', null=True)),
            ],
            options={
                'db_table': 'order_listproduct',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProductListmaterial',
            fields=[
                ('productid', models.OneToOneField(db_column='ProductID', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='wood_producing.product')),
                ('productindex', models.IntegerField(db_column='ProductIndex')),
                ('listmaterial', models.IntegerField(blank=True, db_column='ListMaterial', null=True)),
            ],
            options={
                'db_table': 'product_listmaterial',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StorageListmaterial',
            fields=[
                ('storageid', models.OneToOneField(db_column='StorageID', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='wood_producing.storage')),
                ('storageindex', models.IntegerField(db_column='StorageIndex')),
                ('listmaterial', models.IntegerField(blank=True, db_column='ListMaterial', null=True)),
            ],
            options={
                'db_table': 'storage_listmaterial',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TaskListprogress',
            fields=[
                ('taskid', models.OneToOneField(db_column='TaskID', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='wood_producing.task')),
                ('taskindex', models.IntegerField(db_column='TaskIndex')),
                ('listprogress', models.IntegerField(blank=True, db_column='ListProgress', null=True)),
            ],
            options={
                'db_table': 'task_listprogress',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TaskListrequest',
            fields=[
                ('taskid', models.OneToOneField(db_column='TaskID', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='wood_producing.task')),
                ('taskindex', models.IntegerField(db_column='TaskIndex')),
                ('listrequest', models.IntegerField(blank=True, db_column='ListRequest', null=True)),
            ],
            options={
                'db_table': 'task_listrequest',
                'managed': False,
            },
        ),
    ]
