# Generated by Django 3.1.7 on 2021-05-09 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wood_producing', '0002_remove_user_companyid'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='name',
            field=models.CharField(db_column='Name', default='', max_length=255),
        ),
    ]
