# Generated by Django 3.1.7 on 2021-05-13 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wood_producing', '0004_order_duedate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='customer',
        ),
    ]
