# Generated by Django 3.1.7 on 2021-05-13 13:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wood_producing', '0006_auto_20210513_1323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storage',
            name='manager',
            field=models.ForeignKey(db_column='Manager', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
