# Generated by Django 3.1.7 on 2021-05-13 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wood_producing', '0007_auto_20210513_1328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderedproduct',
            name='productexportedid',
            field=models.ForeignKey(db_column='ProductExportedID', null=True, on_delete=django.db.models.deletion.CASCADE, to='wood_producing.productexported'),
        ),
    ]
