# Generated by Django 3.1.7 on 2021-05-13 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wood_producing', '0008_auto_20210513_1331'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='progress',
            field=models.ForeignKey(db_column='progress', null=True, on_delete=django.db.models.deletion.CASCADE, to='wood_producing.progress'),
        ),
    ]
