# Generated by Django 3.1.7 on 2021-05-13 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wood_producing', '0009_task_progress'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderedproduct',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='wood_producing.order'),
        ),
    ]
