# Generated by Django 3.1.7 on 2021-05-14 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wood_producing', '0010_orderedproduct_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='name',
            field=models.CharField(db_column='name', default='task abc', max_length=255),
            preserve_default=False,
        ),
    ]
