# Generated by Django 3.1.7 on 2021-05-14 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wood_producing', '0011_task_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='priority',
            field=models.IntegerField(db_column='priority', default=0),
        ),
    ]
