# Generated by Django 3.1.7 on 2021-05-14 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wood_producing', '0012_task_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='quantity',
            field=models.IntegerField(db_column='quantity', default=0),
        ),
    ]
