# Generated by Django 3.1.7 on 2021-05-14 01:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('wood_producing', '0013_task_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='estimated',
            field=models.DateTimeField(db_column='estimated', default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
