# Generated by Django 3.1.7 on 2021-05-14 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wood_producing', '0016_auto_20210514_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(db_column='priority', default='low', max_length=10),
        ),
    ]
