# Generated by Django 3.1.7 on 2021-05-15 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wood_producing', '0017_auto_20210514_1728'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.CharField(db_column='status', default='doing', max_length=100),
        ),
    ]
