# Generated by Django 3.1.7 on 2021-05-15 16:02

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('wood_producing', '0018_task_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materialrequestlistmaterial',
            name='materialrequestindex',
        ),
        migrations.RemoveField(
            model_name='requestedmaterial',
            name='material',
        ),
        migrations.RemoveField(
            model_name='taskprogress',
            name='progress',
        ),
        migrations.RemoveField(
            model_name='taskprogress',
            name='task',
        ),
        migrations.AddField(
            model_name='materialrequest',
            name='is_approved',
            field=models.BooleanField(db_column='is_approve', default=False),
        ),
        migrations.AddField(
            model_name='materialrequest',
            name='material',
            field=models.ForeignKey(db_column='material', default=1, on_delete=django.db.models.deletion.CASCADE, to='wood_producing.material'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='create_at',
            field=models.DateTimeField(db_column='create_at', default=datetime.datetime(2021, 5, 15, 16, 2, 15, 208471, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='taskprogress',
            name='progressid',
            field=models.ForeignKey(db_column='ProgressID', on_delete=django.db.models.deletion.CASCADE, to='wood_producing.progress'),
        ),
        migrations.AlterField(
            model_name='taskprogress',
            name='taskid',
            field=models.ForeignKey(db_column='TaskID', on_delete=django.db.models.deletion.CASCADE, to='wood_producing.task'),
        ),
    ]
