# Generated by Django 3.1.7 on 2021-05-15 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wood_producing', '0020_task_update_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskprogress',
            name='percentage',
            field=models.IntegerField(default=0),
        ),
    ]
