# Generated by Django 3.1.7 on 2021-05-15 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wood_producing', '0021_taskprogress_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialinproduct',
            name='quantity',
            field=models.IntegerField(default=2),
        ),
    ]
