# Generated by Django 3.1.7 on 2021-05-16 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wood_producing', '0022_materialinproduct_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialinproduct',
            name='description',
            field=models.CharField(default='is a main material', max_length=300),
        ),
    ]
