# Generated by Django 3.1.7 on 2021-05-16 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wood_producing', '0024_auto_20210516_0009'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialrequest',
            name='quantity',
            field=models.IntegerField(default=10),
        ),
    ]
