# Generated by Django 3.1.7 on 2021-05-16 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wood_producing', '0025_materialrequest_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskprogress',
            name='enddate',
            field=models.DateTimeField(blank=True, db_column='EndDate', null=True),
        ),
        migrations.AlterField(
            model_name='taskprogress',
            name='startdate',
            field=models.DateTimeField(blank=True, db_column='StartDate', null=True),
        ),
    ]
