# Generated by Django 3.1.7 on 2021-05-16 08:20

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('wood_producing', '0027_auto_20210516_0801'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materialofproviderinstorage',
            name='requestedmaterialid',
        ),
        migrations.AddField(
            model_name='order',
            name='create_at',
            field=models.DateTimeField(db_column='create_at', default=datetime.datetime(2021, 5, 16, 8, 20, 31, 100184, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='requestedmaterial',
            name='materialofproviderinstorageid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='wood_producing.materialofproviderinstorage'),
        ),
    ]
