# Generated by Django 3.1.7 on 2021-05-16 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wood_producing', '0029_auto_20210516_0926'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='importbilllistmaterial',
            name='importbillid',
        ),
        migrations.RemoveField(
            model_name='materialrequestlistmaterial',
            name='materialrequestid',
        ),
        migrations.RemoveField(
            model_name='orderlistproduct',
            name='orderid',
        ),
        migrations.RemoveField(
            model_name='productlistmaterial',
            name='productid',
        ),
        migrations.RemoveField(
            model_name='storagelistmaterial',
            name='storageid',
        ),
        migrations.RemoveField(
            model_name='tasklistprogress',
            name='taskid',
        ),
        migrations.RemoveField(
            model_name='tasklistrequest',
            name='taskid',
        ),
        migrations.DeleteModel(
            name='ExportbillListproduct',
        ),
        migrations.DeleteModel(
            name='ImportbillListmaterial',
        ),
        migrations.DeleteModel(
            name='MaterialrequestListmaterial',
        ),
        migrations.DeleteModel(
            name='OrderListproduct',
        ),
        migrations.DeleteModel(
            name='ProductListmaterial',
        ),
        migrations.DeleteModel(
            name='StorageListmaterial',
        ),
        migrations.DeleteModel(
            name='TaskListprogress',
        ),
        migrations.DeleteModel(
            name='TaskListrequest',
        ),
    ]
