# Generated by Django 3.1.7 on 2021-05-16 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wood_producing', '0030_auto_20210516_1355'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productexported',
            name='exportbillid',
        ),
        migrations.RemoveField(
            model_name='importedmaterial',
            name='material',
        ),
        migrations.RemoveField(
            model_name='materialofprovider',
            name='importedmaterialid',
        ),
        migrations.RemoveField(
            model_name='orderedproduct',
            name='productexportedid',
        ),
        migrations.RemoveField(
            model_name='product',
            name='discriminator',
        ),
        migrations.RemoveField(
            model_name='product',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='task',
            name='product',
        ),
        migrations.AddField(
            model_name='importedmaterial',
            name='materialofprovider',
            field=models.ForeignKey(blank=True, db_column='Material', null=True, on_delete=django.db.models.deletion.CASCADE, to='wood_producing.materialofprovider'),
        ),
        migrations.AlterField(
            model_name='orderedproduct',
            name='storageid',
            field=models.ForeignKey(db_column='StorageID', null=True, on_delete=django.db.models.deletion.CASCADE, to='wood_producing.storage'),
        ),
        migrations.DeleteModel(
            name='Exportbill',
        ),
        migrations.DeleteModel(
            name='Productexported',
        ),
    ]
