# Generated by Django 3.1.7 on 2021-05-17 03:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wood_producing', '0032_auto_20210517_0304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importbill',
            name='manager',
            field=models.ForeignKey(blank=True, db_column='Manager', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
