# Generated by Django 3.1.7 on 2021-05-17 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wood_producing', '0033_auto_20210517_0307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialrequest',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, db_column='create_at'),
        ),
        migrations.AlterField(
            model_name='order',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, db_column='create_at'),
        ),
        migrations.AlterField(
            model_name='task',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, db_column='create_at'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.SmallIntegerField(choices=[(3, 'FOREMAN'), (1, 'PRODUCING_MANAGER'), (2, 'STORAGE_MANAGER'), (4, 'DIRECTOR'), (5, 'SELLER')], default=3),
        ),
    ]
