# Generated by Django 3.1.7 on 2021-05-17 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wood_producing', '0034_auto_20210517_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialrequest',
            name='create_at',
            field=models.DateTimeField(auto_now=True, db_column='create_at'),
        ),
        migrations.AlterField(
            model_name='order',
            name='create_at',
            field=models.DateTimeField(auto_now=True, db_column='create_at'),
        ),
        migrations.AlterField(
            model_name='task',
            name='create_at',
            field=models.DateTimeField(auto_now=True, db_column='create_at'),
        ),
    ]
