# Generated by Django 3.1.7 on 2021-05-17 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wood_producing', '0035_auto_20210517_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, db_column='create_at'),
        ),
        migrations.AlterField(
            model_name='task',
            name='update_at',
            field=models.DateTimeField(auto_now=True, db_column='update_at'),
        ),
    ]
