# Generated by Django 3.1.7 on 2021-05-17 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wood_producing', '0036_auto_20210517_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(db_column='status', default='pending', max_length=100),
        ),
    ]
