# Generated by Django 3.1.7 on 2021-05-18 02:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wood_producing', '0037_auto_20210517_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importbill',
            name='providerid',
            field=models.ForeignKey(db_column='ProviderID', on_delete=django.db.models.deletion.CASCADE, to='wood_producing.provider'),
        ),
        migrations.AlterField(
            model_name='importedmaterial',
            name='importbillid',
            field=models.ForeignKey(db_column='ImportBillID', on_delete=django.db.models.deletion.CASCADE, to='wood_producing.importbill'),
        ),
        migrations.AlterField(
            model_name='materialinproduct',
            name='materialid',
            field=models.ForeignKey(db_column='MaterialID', on_delete=django.db.models.deletion.CASCADE, to='wood_producing.material'),
        ),
        migrations.AlterField(
            model_name='materialinproduct',
            name='productid',
            field=models.ForeignKey(db_column='ProductID', on_delete=django.db.models.deletion.CASCADE, to='wood_producing.product'),
        ),
        migrations.AlterField(
            model_name='materialofprovider',
            name='materialid',
            field=models.ForeignKey(db_column='MaterialID', on_delete=django.db.models.deletion.CASCADE, to='wood_producing.material'),
        ),
        migrations.AlterField(
            model_name='materialofprovider',
            name='providerid',
            field=models.ForeignKey(db_column='ProviderID', on_delete=django.db.models.deletion.CASCADE, to='wood_producing.provider'),
        ),
        migrations.AlterField(
            model_name='materialofproviderinstorage',
            name='materialofproviderid',
            field=models.ForeignKey(db_column='MaterialOfProviderID', on_delete=django.db.models.deletion.CASCADE, to='wood_producing.materialofprovider'),
        ),
        migrations.AlterField(
            model_name='materialofproviderinstorage',
            name='storageid',
            field=models.ForeignKey(db_column='StorageID', on_delete=django.db.models.deletion.CASCADE, to='wood_producing.storage'),
        ),
        migrations.AlterField(
            model_name='materialrequest',
            name='storageid',
            field=models.ForeignKey(db_column='StorageID', null=True, on_delete=django.db.models.deletion.CASCADE, to='wood_producing.storage'),
        ),
        migrations.AlterField(
            model_name='order',
            name='customerid',
            field=models.ForeignKey(db_column='CustomerID', on_delete=django.db.models.deletion.CASCADE, to='wood_producing.customer'),
        ),
        migrations.AlterField(
            model_name='order',
            name='userid',
            field=models.ForeignKey(db_column='UserID', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='requestedmaterial',
            name='materialrequestid',
            field=models.ForeignKey(db_column='MaterialRequestID', on_delete=django.db.models.deletion.CASCADE, to='wood_producing.materialrequest'),
        ),
        migrations.AlterField(
            model_name='storage',
            name='companyid',
            field=models.ForeignKey(db_column='CompanyID', on_delete=django.db.models.deletion.CASCADE, to='wood_producing.company'),
        ),
        migrations.AlterField(
            model_name='task',
            name='orderedproductid',
            field=models.ForeignKey(db_column='OrderedProductID', on_delete=django.db.models.deletion.CASCADE, to='wood_producing.orderedproduct'),
        ),
        migrations.AlterField(
            model_name='task',
            name='userid',
            field=models.ForeignKey(db_column='UserID', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='companyid',
            field=models.ForeignKey(db_column='CompanyID', on_delete=django.db.models.deletion.CASCADE, to='wood_producing.company'),
        ),
    ]
